# Название workflow
name: testops_PHPunit

# переменные окружения
env:
    PHP_VERSION: "8.3"
    ALLURE_ENDPOINT: https://demo.qatools.cloud/
    ENDPOINT: https://demo.qatools.cloud/
    ALLURE_PROJECT_ID: 165
    ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
    #ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
    ALLURE_RESULTS: "build/allure-results"
    BROWSER: ${{ inputs.BROWSER || 'OperaGX' }}
    OS: ${{ inputs.OS || 'Win_11' }}
    #LAUNCH_TYPE: ${{ inputs.LAUNCH_TYPE || 'push' }}
    BRANCH: ${{ github.ref_name }}

# Триггеры для запуска workflow
on:
#пуш и пулл реквест
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
# вручную
    workflow_dispatch:
        inputs:
          ENDPOINT:
            description: "Endpoint"
            required: false
            default: "https://demo.qatools.cloud/"
          BROWSER:
            description: Browser
            required: false
            default: "OperaGX"
          OS:
            description: OS
            required: false
            default: "Win_11"
          #LAUNCH_TYPE:
          #  description: LAUNCH_TYPE
          #  required: false
          #  default: "manual"
          ALLURE_JOB_RUN_ID:
            description: "ALLURE_JOB_RUN_ID - service parameter (leave blank)"
            required: false
            default: ""
          ALLURE_USERNAME:
            description: "ALLURE_USERNAME - service parameter (leave blank)"
            required: false
            default: ""
          BRANCH:
            description: "Git branch (filled automatically)"
            required: false
            default: ""
  

jobs:
    autotests:
        name: Run tests
        runs-on: ubuntu-latest
        # указываем ветку на которой запускаем воркфлоу
        env:
          BRANCH: ${{ inputs.BRANCH != '' && inputs.BRANCH || github.ref_name }}
          #BRANCH: ${{ github.ref_name }}
        
        steps:
            - uses: actions/checkout@v4
            
            # подготовка окружения для всего воркфлоу
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ env.PHP_VERSION }}
                extensions: dom, mbstring
            
            # установка зависимостей через composer
            - name: Install dependencies
              run: composer install --no-progress --prefer-dist

            # устанока allurectl (связующее звено с ТестОпс)
            - name: Install allurectl
              uses: allure-framework/setup-allurectl@v1
              with:
                allure-endpoint: ${{ env.ALLURE_ENDPOINT }}
                allure-token: ${{ env.ALLURE_TOKEN }}
                allure-project-id: ${{ env.ALLURE_PROJECT_ID }}

            # создаем директорию для результатов
            - name: Ensure allure-results directory exists
              run: |
                mkdir -p ${{ env.ALLURE_RESULTS }}

            # запускаем тесты под присмортом allurectl     
            - name: Run tests with allurectl
              run: |
                allurectl watch -- ./vendor/bin/phpunit --bootstrap vendor/autoload.php
              continue-on-error: true
              env:
                BRANCH: ${{ github.ref_name }}
                #ENDPOINT: ${{ github.event.inputs.ENDPOINT}}
                ENDPOINT: ${{ env.ALLURE_ENDPOINT }}
                BROWSER: ${{ github.event.inputs.BROWSER}}
                OS: ${{ github.event.inputs.OS}}
                ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}

            # загружаем файлы в ТестОпс
            #- name: Upload results to Allure TestOps
            #  run: |
            #    allurectl upload --endpoint="${{ env.ALLURE_ENDPOINT }}" \
            #                       --project-id="${{ env.ALLURE_PROJECT_ID }}" \
            #                       --token="${{ env.ALLURE_TOKEN }}" \
            #                       ${{ env.ALLURE_RESULTS }}
